### ISSUE TITLE
Admin panel not responsive

### ISSUE THREAD

**Issue by aiouy** [start-angular/ani-theme#1]
Beautiful theme.

The admin panel is not responsive however. I'm looking for the hamburger menu but it's not showing on window resize and the entire menu disappears.

**Comment by sanketsahu** [comment]
Screenshot would help.

**Comment by zhouhao27** [comment]
Got the same issue. Here is the screenshot: (no hamburger menu shown)

![screen shot 2015-10-02 at 11 57 17 am](https://cloud.githubusercontent.com/assets/8099731/10239204/d0e16f82-68fc-11e5-8669-fe0ba4722312.png)

**Comment by sanketsahu** [comment]
I am not maintaining this for a while. The theme is very basic and you can add it yourself. If you add it, do send pull-request, I will merge it. It will help others.
