### ISSUE TITLE
No Auto-complete text-box component?

### ISSUE THREAD

**Issue by ksabariraj** [start-angular/ani-theme#2]
No Auto-complete text-box component in theme?

**Comment by sanketsahu** [comment]
That's not available here in the free edition. It will be available on the premium version soon
http://www.strapui.com/themes/ani-angularjs-theme/

**Comment by ksabariraj** [comment]
Thanks for your reply. We already purchased premium version. Do we need to download again after you release the version?

**Comment by sanketsahu** [comment]
You will be notified via email when new versions are released and it will
be a free upgrade for the existing buyers.
