### ISSUE TITLE
Unable to build bower css

### ISSUE THREAD

**Issue by buddalasunil999** [start-angular/ani-theme#4]
Hi,

I'm using the gulp file provided in this project. I ran into one problem, it's not building the css file that I included in index.html which is part of bower components. Can you help me resolve the problem.

**Comment by sanketsahu** [comment]
Make sure, it's between the wiredep build tags. It should build fine.

**Comment by buddalasunil999** [comment]
But it's not working. Here's my html. I included it between bower tags.

 
    
    <link rel="stylesheet" href="../bower_components/chosen/chosen.min.css" />
